Instance: GOFSH-GENERATED-ID-0
InstanceOf: Bundle
Usage: #example
* identifier.system = "urn:ietf:rfc:4122"
* identifier.value = "3e594fe5-3ed5-4305-a214-99c87e1f3bfa"
* type = #document
* timestamp = "2025-05-11T10:18:14.632+00:00"
* entry[0].fullUrl = "http://example.org/Composition/composition-swart"
* entry[=].resource = composition-swart
* entry[+].fullUrl = "http://example.org/Condition/condition-growth"
* entry[=].resource = condition-growth
* entry[+].fullUrl = "http://example.org/Condition/condition-meerling"
* entry[=].resource = condition-meerling
* entry[+].fullUrl = "http://example.org/Encounter/ziekenhuisopname-swart"
* entry[=].resource = ziekenhuisopname-swart
* entry[+].fullUrl = "http://example.org/Observation/alcohol-swart"
* entry[=].resource = alcohol-swart
* entry[+].fullUrl = "http://example.org/Observation/bloeddruk-swart"
* entry[=].resource = bloeddruk-swart
* entry[+].fullUrl = "http://example.org/Observation/gewicht-swart"
* entry[=].resource = gewicht-swart
* entry[+].fullUrl = "http://example.org/Observation/lab-swart-1"
* entry[=].resource = lab-swart-1
* entry[+].fullUrl = "http://example.org/Observation/lab-swart-2"
* entry[=].resource = lab-swart-2
* entry[+].fullUrl = "http://example.org/Observation/lab-swart-3"
* entry[=].resource = lab-swart-3
* entry[+].fullUrl = "http://example.org/Observation/lab-swart-4"
* entry[=].resource = lab-swart-4
* entry[+].fullUrl = "http://example.org/Observation/lab-swart-5"
* entry[=].resource = lab-swart-5
* entry[+].fullUrl = "http://example.org/Observation/lab-swart-6"
* entry[=].resource = lab-swart-6
* entry[+].fullUrl = "http://example.org/Observation/levenvoelen-swart"
* entry[=].resource = levenvoelen-swart
* entry[+].fullUrl = "http://example.org/Observation/tobacco-swart"
* entry[=].resource = tobacco-swart
* entry[+].fullUrl = "http://example.org/Organization/organization-sophia"
* entry[=].resource = organization-sophia
* entry[+].fullUrl = "http://example.org/Patient/patient-swart"
* entry[=].resource = patient-swart
* entry[+].fullUrl = "http://example.org/Procedure/sectio-swart"
* entry[=].resource = sectio-swart